version: '3.9'

services:

    nginx:
      image: nginx:latest
      ports:
          - '80:80'
      volumes:
          - ./nginx:/etc/nginx/conf.d
          - ./logs/nginx:/var/log/nginx
          - ./wordpress:/var/www/html
      links:
          - wordpress
      restart: always
      environment:
        - FOO=bar
      logging:
        driver: loki
        options:
          loki-url: http://localhost:3100/loki/api/v1/push
      networks:
        - service-network

    mysql:
      image: mariadb
      ports:
          - '3306:3306'
      volumes:
          - ./db-data:/var/lib/mysql
      environment:
          - MYSQL_ROOT_PASSWORD=aqwe123
      restart: always
      networks:
        - service-network

    wordpress:
      image: wordpress:4.7.1-php7.0-fpm
      ports:
          - '9000:9000'
      volumes:
          - ./wordpress:/var/www/html
      environment:
          - WORDPRESS_DB_NAME=wpdb
          - WORDPRESS_TABLE_PREFIX=wp_
          - WORDPRESS_DB_HOST=mysql
          - WORDPRESS_DB_PASSWORD=aqwe123
      links:
          - mysql
      restart: always
      networks:
        - service-network
  
    grafana:
      image: grafana/grafana:7.2.2
      volumes:
      - ./config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      ports:
      - "3000:3000"
      networks:
        - service-network
    
    loki:
      image: grafana/loki:2.0.0
      volumes:
        - ./config/loki.yaml:/etc/config/loki.yaml
      entrypoint:
        - /usr/bin/loki
        - -config.file=/etc/config/loki.yaml
      ports:
        - "3100:3100"
      networks:
        - service-network
        
    logger-app:
      image: ctovena/logger:0.12
      logging:
        driver: loki
        options:
          loki-url: http://localhost:3100/loki/api/v1/push

    promtail:
      image: grafana/promtail:2.2.1
      volumes:
        - /var/log:/var/log
      command: -config.file=/etc/promtail/config.yml
      networks:
        - service-network

       
volumes:
    db_data:

networks: 
    service-network:
        name: service-network
        driver: bridge